name: Test and Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello, world!"
      - name: fecha
        run: date
      - name: Muestreme el archivo del directorio
        run: ls -la
        